[project]
name = "api-study-fr-er"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi>=0.121.3",
    "uvicorn>=0.38.0",
]
